// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by generate-i18n-resources.js

import ar_common from "../localization/ar/common.json";
import de_common from "../localization/de/common.json";
import en_common from "../localization/en/common.json";
import en_settings from "../localization/en/settings.json";
import es_common from "../localization/es/common.json";
import fa_common from "../localization/fa/common.json";
import fr_common from "../localization/fr/common.json";
import hi_common from "../localization/hi/common.json";
import it_common from "../localization/it/common.json";
import ja_common from "../localization/ja/common.json";
import ko_common from "../localization/ko/common.json";
import ps_common from "../localization/ps/common.json";
import pt_common from "../localization/pt/common.json";
import ru_common from "../localization/ru/common.json";
import tr_common from "../localization/tr/common.json";
import ur_common from "../localization/ur/common.json";
import zh_common from "../localization/zh/common.json";

export const resources = {
  ar: {
    common: ar_common,
    settings: {},
  },
  de: {
    common: de_common,
    settings: {},
  },
  en: {
    common: en_common,
    settings: en_settings,
  },
  es: {
    common: es_common,
    settings: {},
  },
  fa: {
    common: fa_common,
    settings: {},
  },
  fr: {
    common: fr_common,
    settings: {},
  },
  hi: {
    common: hi_common,
    settings: {},
  },
  it: {
    common: it_common,
    settings: {},
  },
  ja: {
    common: ja_common,
    settings: {},
  },
  ko: {
    common: ko_common,
    settings: {},
  },
  ps: {
    common: ps_common,
    settings: {},
  },
  pt: {
    common: pt_common,
    settings: {},
  },
  ru: {
    common: ru_common,
    settings: {},
  },
  tr: {
    common: tr_common,
    settings: {},
  },
  ur: {
    common: ur_common,
    settings: {},
  },
  zh: {
    common: zh_common,
    settings: {},
  },
};

export const languages = [
  "ar",
  "de",
  "en",
  "es",
  "fa",
  "fr",
  "hi",
  "it",
  "ja",
  "ko",
  "ps",
  "pt",
  "ru",
  "tr",
  "ur",
  "zh"
] as const;
export const namespaces = ["common","settings"] as const;

export type LanguageKey = (typeof languages)[number];
export type Namespace = (typeof namespaces)[number];
