// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by generate-i18n-resources.js

import ar_common from "../localization/ar/common.json";
import ar_settings from "../localization/ar/settings.json";
import de_common from "../localization/de/common.json";
import de_settings from "../localization/de/settings.json";
import en_common from "../localization/en/common.json";
import en_settings from "../localization/en/settings.json";
import es_common from "../localization/es/common.json";
import es_settings from "../localization/es/settings.json";
import fa_common from "../localization/fa/common.json";
import fa_settings from "../localization/fa/settings.json";
import fr_common from "../localization/fr/common.json";
import fr_settings from "../localization/fr/settings.json";
import hi_common from "../localization/hi/common.json";
import hi_settings from "../localization/hi/settings.json";
import it_common from "../localization/it/common.json";
import it_settings from "../localization/it/settings.json";
import ja_common from "../localization/ja/common.json";
import ja_settings from "../localization/ja/settings.json";
import ko_common from "../localization/ko/common.json";
import ko_settings from "../localization/ko/settings.json";
import ps_common from "../localization/ps/common.json";
import ps_settings from "../localization/ps/settings.json";
import pt_common from "../localization/pt/common.json";
import pt_settings from "../localization/pt/settings.json";
import ru_common from "../localization/ru/common.json";
import ru_settings from "../localization/ru/settings.json";
import tr_common from "../localization/tr/common.json";
import tr_settings from "../localization/tr/settings.json";
import ur_common from "../localization/ur/common.json";
import ur_settings from "../localization/ur/settings.json";
import zh_common from "../localization/zh/common.json";
import zh_settings from "../localization/zh/settings.json";
import th_common from "../localization/th/common.json";
import id_common from "../localization/id/common.json";
import vi_common from "../localization/vi/common.json";
import sw_common from "../localization/sw/common.json";
import ha_common from "../localization/ha/common.json";
import bn_common from "../localization/bn/common.json";

export const resources = {
  ar: {
    common: ar_common,
    settings: ar_settings,
  },
  de: {
    common: de_common,
    settings: de_settings,
  },
  en: {
    common: en_common,
    settings: en_settings,
  },
  es: {
    common: es_common,
    settings: es_settings,
  },
  fa: {
    common: fa_common,
    settings: fa_settings,
  },
  fr: {
    common: fr_common,
    settings: fr_settings,
  },
  hi: {
    common: hi_common,
    settings: hi_settings,
  },
  it: {
    common: it_common,
    settings: it_settings,
  },
  ja: {
    common: ja_common,
    settings: ja_settings,
  },
  ko: {
    common: ko_common,
    settings: ko_settings,
  },
  ps: {
    common: ps_common,
    settings: ps_settings,
  },
  pt: {
    common: pt_common,
    settings: pt_settings,
  },
  ru: {
    common: ru_common,
    settings: ru_settings,
  },
  tr: {
    common: tr_common,
    settings: tr_settings,
  },
  ur: {
    common: ur_common,
    settings: ur_settings,
  },
  zh: {
    common: zh_common,
    settings: zh_settings,
  },
  th: {
    common: th_common,
    settings: {},
  },
  id: {
    common: id_common,
    settings: {},
  },
  vi: {
    common: vi_common,
    settings: {},
  },
  sw: {
    common: sw_common,
    settings: {},
  },
  ha: {
    common: ha_common,
    settings: {},
  },
  bn: {
    common: bn_common,
    settings: {},
  },
};

export const languages = [
  "ar",
  "de",
  "en",
  "es",
  "fa",
  "fr",
  "hi",
  "it",
  "ja",
  "ko",
  "ps",
  "pt",
  "ru",
  "tr",
  "ur",
  "zh",
  "th",
  "id",
  "vi",
  "sw",
  "ha",
  "bn",
] as const;
export const namespaces = ["common", "settings"] as const;

export type LanguageKey = (typeof languages)[number];
export type Namespace = (typeof namespaces)[number];
